### ISSUE TITLE
Please fix the typo in the name!!!

### ISSUE THREAD

**Issue by nemkin** [KlevisImeri/Integrator2#1]

**Comment by nemkin** [comment]
@KlevisImeri

**Comment by nemkin** [comment]
![](https://media.giphy.com/media/YmVNzDnboB0RQEpmLr/giphy.gif)

**Comment by KlevisImeri** [comment]
![](https://media.giphy.com/media/o0vwzuFwCGAFO/giphy.gif)
Fix #1

**Comment by nemkin** [comment]
It still says Integratior2 to me @KlevisImeri 😅
